name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
    GOPROXY: direct
    GOVCS: private:all,public:all
    CGO_ENABLED: 1

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        debian:buster
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Get dependencies
      run: |
        apt-get update
        apt-get install -y git build-essential pkg-config bzr libzmq3-dev
        go get -v -t ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Provide binary as artifact
      uses: actions/upload-artifact@v2
      with:
        name: tie-threatbus-bridge-executable
        path: tie-threatbus-bridge
